FROM node:lts-alpine

EXPOSE 5000

WORKDIR /usr/src/app

RUN npm install -g serve

COPY package.json package-lock.json .

RUN npm install

COPY . .

RUN npm run build

RUN useradd -m feuser

USER feuser

CMD ["serve", "-s", "-l", "5000", "build"]