version: "3.8"

services:
  frontend:
    image: frontend
    ports:
      - 5001:5000
  backend:
    image: backend
    ports:
      - 8080:8080
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: example
  redis:
    image: redis:alpine
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    container_name: db_backend
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database:
