version: "3.8"

services:
  frontend:
    image: frontend
    environment:
      REACT_APP_BACKEND_URL: http://localhost/api
  backend:
    image: backend
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: example
      REQUEST_ORIGIN: http://localhost
  redis:
    image: redis:alpine
    volumes:
      - ./redis:/data
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./database:/var/lib/postgresql/data
  nginx:
    image: nginx:1.19-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
